### ISSUE TITLE
repo update for 2020

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/SOE-MAFMC#4]
How should we archive the 2019 SOE documents before starting 2020?
We will name the 2020 docs with the year, but should the 2019 stuff go to an archive folder in this repository? Along with its images and scripts?
And how will that affect the tech-doc?

**Comment by sgaichas** [comment]
The plan

- [x] Add specific ecodata version to 2019 SOEs

- [x] release full 2019 repo with numbering scheme

- [x] semantic versioning first digit is a breaking change

- [x] after release burn the repo and start over for 2020

**Comment by sgaichas** [comment]
Tech doc dependency to be broken, Tech doc only dependent on ecodata

**Comment by slarge** [comment]
I propose the following semantic schedule, which might vary a bit from our conversation this afternoon.
<annual release>.<update>.<bug fix> 
So, for 2020, the initial release for the SSC will be: v1.0.0 and the final update would be v1.5.0. If there is a bug to fix, the last digit would increase, e.g., v1.0.1 or v1.5.1.
2021 would be v2.0.0 followed by v2.5.0 and so forth. 

Thoughts?

**Comment by slucey** [comment]
Makes sense to me.

**Comment by sgaichas** [comment]
The numbering scheme sounds good to me too.

Thanks to @kimberly-bastille for releasing 2019. We now commence 2020!
